Loss
	validation       	 (min:    0.067, max:    0.067, cur:    0.067)
	training         	 (min:    0.108, max:    0.108, cur:    0.108)
Loss
	validation       	 (min:    0.002, max:    0.067, cur:    0.003)
	training         	 (min:    0.002, max:    0.108, cur:    0.002)
Loss
	validation       	 (min:    0.002, max:    0.067, cur:    0.004)
	training         	 (min:    0.002, max:    0.108, cur:    0.003)
Time elapsed: 358.88s.
Number of trainable model parameters: 5552, number of training samples: 929
Used batches of 50.
Time taken: 358.9355821609497s
Untrustworthy in train:	0	(low: 0, high: 0)
Untrustworthy in test:	588	(low: 509, high: 79)
Untrustworthy in val:	1	(low: 1, high: 0)
----------------------
Total untrustworthy:	589
Untrustworthy in train:	0	(low: 0, high: 0)
Untrustworthy in test:	563	(low: 522, high: 41)
Untrustworthy in val:	1	(low: 1, high: 0)
----------------------
Total untrustworthy:	564
C:\Users\aolux\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\aolux\anaconda3\lib\site-packages\numpy\core\_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
C:\Users\aolux\anaconda3\lib\site-packages\numpy\core\_methods.py:264: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
C:\Users\aolux\anaconda3\lib\site-packages\numpy\core\_methods.py:222: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',
C:\Users\aolux\anaconda3\lib\site-packages\numpy\core\_methods.py:256: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
C:\Users\aolux\anaconda3\lib\site-packages\seaborn\distributions.py:2657: RuntimeWarning: Mean of empty slice.
  line, = ax.plot(a.mean(), 0)
C:\Users\aolux\anaconda3\lib\site-packages\numpy\lib\histograms.py:906: RuntimeWarning: invalid value encountered in true_divide
  return n/db/n.sum(), bin_edges
C:\Users\aolux\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\aolux\anaconda3\lib\site-packages\numpy\core\_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
C:\Users\aolux\anaconda3\lib\site-packages\numpy\core\_methods.py:264: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
C:\Users\aolux\anaconda3\lib\site-packages\numpy\core\_methods.py:222: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',
C:\Users\aolux\anaconda3\lib\site-packages\numpy\core\_methods.py:256: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
C:\Users\aolux\anaconda3\lib\site-packages\seaborn\distributions.py:2657: RuntimeWarning: Mean of empty slice.
  line, = ax.plot(a.mean(), 0)
C:\Users\aolux\anaconda3\lib\site-packages\numpy\lib\histograms.py:906: RuntimeWarning: invalid value encountered in true_divide
  return n/db/n.sum(), bin_edges
OOD lower:	835
OOD upper:	195
Train:		929
Test:		863
Val:		104
Unused:		82
Total:		1978 (of 1978)
[34m[1mwandb[39m[22m: [33mWARNING[39m Calling wandb.login() after wandb.init() has no effect.